server:
  port: 8001 #服务端口
#spring相关配置
spring:
  application:
    name: springcloud-payment  #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver  #数据库驱动包
    url: jdbc:mysql://localhost:3306/db01?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
#mybatis:配置
mybatis:
  mapperLocations: classpath:com/jinhai/springcloud/dao/*.xml
  type-aliases-package: com.jinhai.springcloud.pojo    # 所有pojo别名类所在包

#eureka配置
eureka:
  client:
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
